AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:
  VPCId:
    Type: String

  DBSecurityGroup:
    Type: String

  PrivateSubnetDB01:
    Type: String

  PrivateSubnetDB02:
    Type: String

  DatabaseName:
    Type: String

  MasterUsername:
    Type: String

  MasterUserPassword:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
        - !Ref PrivateSubnetDB01
        - !Ref PrivateSubnetDB02
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-DBSubnetGroup
        - Key: aws-exam-resource
          Value: true

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: !Ref DatabaseName
      DBClusterIdentifier: AuroraCluster
      DBClusterParameterGroupName: default.aurora-mysql5.7
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: aurora-mysql
      EngineMode: provisioned
      EngineVersion: 5.7.mysql_aurora.2.10.2
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      StorageEncrypted: True
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Aurora-Cluster
        - Key: aws-exam-resource
          Value: true
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup

  RDSDBInstance1:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.t3.small
      DBParameterGroupName: default.aurora-mysql5.7
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: aurora-mysql

  RDSDBInstance2:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.t3.small
      DBParameterGroupName: default.aurora-mysql5.7
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: aurora-mysql

Outputs:
  DBHost:
    Value: !GetAtt AuroraCluster.Endpoint.Address
