AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VPCId:
    Type: String
  ALBSecurityGroup:
    Type: String
  PublicSubnet01:
    Type: String
  PublicSubnet02:
    Type: String
  Certification:
    Type: String

Resources:
  ContentsALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: True
        - Key: access_logs.s3.bucket
          Value: exam-alb-accesslog
        - Key: access_logs.s3.prefix
          Value: logs
      Name: ContentsALB
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref PublicSubnet01
        - !Ref PublicSubnet02
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ALB
        - Key: aws-exam-resource
          Value: true

  ContentsALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - !Ref Certification
      DefaultActions:
        - TargetGroupArn: !Ref ContentsTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ContentsALB
      Port: 443
      Protocol: HTTPS

  ContentsALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref ManageTargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /manage/
        # ManageサーバーIP制限
        # - Field: source-ip
        #   SourceIpConfig:
        #     Value:
        #       - X.X.X.X/X
      ListenerArn: !Ref ContentsALBListener
      Priority: 1

  ContentsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: True
      HealthCheckIntervalSeconds: 7
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Name: ContentsTargetGroup
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Contents-tg
        - Key: aws-exam-resource
          Value: true
      TargetType: instance
      VpcId: !Ref VPCId

  ManageTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: True
      HealthCheckIntervalSeconds: 7
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Name: ManageTargetGroup
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Manage-tg
        - Key: aws-exam-resource
          Value: true
      TargetType: instance
      VpcId: !Ref VPCId

Outputs:
  ContentsALBDNSName:
    Value: !GetAtt ContentsALB.DNSName
  ContentsALBCanonicalHostedZoneID:
    Value: !GetAtt ContentsALB.CanonicalHostedZoneID
  ContentsTargetGroup:
    Value: !Ref ContentsTargetGroup
  ManageTargetGroup:
    Value: !Ref ManageTargetGroup
